In [1]:
import numpy as np

from scipy.optimize import nnls

In [2]:
A = np.array([[1, 0], [1, 0], [0, 1]])
b = np.array([2, 1, 1])

In [3]:
A

array([[1, 0],
       [1, 0],
       [0, 1]])

In [4]:
b

array([2, 1, 1])

In [5]:
nnls(A, b)

(array([1.5, 1. ]), 0.7071067811865475)